### ISSUE TITLE
NWDM Cumulus; Observed Data Only Going Back to Jul 30 (14d Lookback)

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/rts-utils#110]
_Issue opened on behalf of another user_

## Information from Email Question

The new cumulus script ran to completion.  But the observed data only went back to Jul 30, even though a 14 day lookback was selected.  Attached is the json file and its contents is also shown below. 

Any ideas why this wouldn’t be going farther into July?

![image](https://user-images.githubusercontent.com/29417036/182637447-faffb280-36bb-4239-8374-13607afd574e.png)

**Comment by jeffsuperglide** [comment]
Email response mentioned that the CAVI cumulus script requires the CAVI time window refreshed using that CAVI button before invoking the cumulus script.  If users change the time window without a refresh, the new time window will not be used in the script.  This could be the issue observed.

**Comment by brettpalmberg** [comment]
Good information @jeffsuperglide. Thanks!

**Comment by brettpalmberg** [comment]
Closing this issue now.
