### ISSUE TITLE
watershed extract doesn't pull data to time of forecast

### ISSUE THREAD

**Issue by adamscarberry** [USACE/rts-utils#65]
Test:
Current time = 5:20pm eastern
CAVI Forecast Time: 01Nov2021 1700 (CAVI Timezone is GMT -5) 

only returned data up to 9:15 am (local/eastern)

extract API endpoint returned data up to "2021-11-01T20:15:00Z" UTC, but same location showed 09:15 am in DSS.

**Comment by adamscarberry** [comment]
DSS values also don't line up.  Quick checks shows API matches USGS.

![image](https://user-images.githubusercontent.com/46494851/139863355-2041d25e-569b-4562-ba10-bcdf686d58ae.png)

**Comment by jeffsuperglide** [comment]
USACE/rts-utils/pull/67 closes USACE/rts-utils/issues/65
