### ISSUE TITLE
[Watershed Extract] Allow Override of Watershed name or handle ugly slug.

### ISSUE THREAD

**Issue by adamscarberry** [USACE/rts-utils#73]
Example: Slug might be `green-river-1` which means the A Part of the DSS records will be the same.  Maybe another config variable to allow the user to override the slug as the watershed name if the slug is ugly.

Maybe something like:
ws_slug = `green-river-1`
ws_name = `green river`  <-- if empty, use ws_slug

Alternatively, you might be able to "automagically" remove any `-1`, `-2`, etc when assigning the watershed name to the DSS A Part.

**Comment by jeffsuperglide** [comment]
PR #74 closes this issue.
